# <span style="color:blue"> Question 6 (continued from Q3 of Tutorial 2): </span>

Get the data set “from sklearn.datasets import load_iris”. Use Python to perform the following
tasks.
1. Split the database into two sets: 74% of samples for training, and 26% of samples for testing. Hint: you might
want to utilize from sklearn.model_selection import train_test_split for the splitting.
2. Construct the target output using one-hot encoding.
3. Perform a linear regression for classification (without inclusion of ridge, utilizing one-hot encoding for the
learning target) and compute the number of test samples that are classified correctly.
4. Using the same training and test sets as in above, perform a 2nd order polynomial regression for classification
(again, without inclusion of ridge, utilizing one-hot encoding for the learning target) and compute the number
of test samples that are classified correctly. Hint: you might want to use from
sklearn.preprocessing import PolynomialFeatures for generation of the polynomial
matrix.

In [20]:
import numpy as np
from numpy.linalg import inv 
from sklearn.datasets import load_iris

iris_dataset = load_iris()
# print(iris_dataset.data)

## (a) split data 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( iris_dataset['data'], iris_dataset['target'], test_size=0.26, random_state=0) 

from sklearn.preprocessing import OneHotEncoder 
onehot_encoder=OneHotEncoder(sparse=False) # Use sparse_output instead of sparse for the new version
reshaped = y_train.reshape(len(y_train), 1) 
Ytr_onehot = onehot_encoder.fit_transform(reshaped) 

## (c) Linear Classification 
bias1 = np.ones((X_train.shape[0], 1)) 
X_train_b = np.concatenate((bias1, X_train), axis = 1) 
w = inv(X_train_b.T @ X_train_b) @ X_train_b.T @ Ytr_onehot 
# print(w) 

# calculate the output based on the estimated w and test input X and then assign to one of the classes based on one hot encoding 
Bias2 = np.ones((X_test.shape[0], 1)) 
X_test_p = np.concatenate((Bias2, X_test), axis = 1) 
yt_est = X_test_p.dot(w); 
yt_cls = [[1 if y == max(x) else 0 for y in x] for x in yt_est ] 
# print(yt_cls) 

# compare the predicted y with the ground truth 
reshaped = y_test.reshape(len(y_test), 1) 
Yts_onehot = onehot_encoder.fit_transform(reshaped)
m1 = np.matrix(Yts_onehot) 
m2 = np.matrix(yt_cls) 
difference = np.abs(m1 - m2) 
# print(difference) 

# calculate the error rate/accuracy 
correct = np.where(~difference.any(axis=1))[0] 
accuracy = len(correct)/len(difference) 
print("For Linear")
print(len(correct)) 
print(accuracy)

## (d) Polynomial Classification 
import numpy as np 
from sklearn.preprocessing import PolynomialFeatures 
poly = PolynomialFeatures(2) 
P = poly.fit_transform(X_train) 
Pt = poly.fit_transform(X_test) 

if P.shape[0] > P.shape[1]: 
    wp = inv(P.T @ P) @ P.T @ Ytr_onehot
else: 
    wp = P.T @ inv(P @ P.T) @ Ytr_onehot 

print("wp=", wp) 

yt_est_p = Pt@wp; 
yt_cls_p = [[1 if y == max(x) else 0 for y in x] for x in yt_est_p ] 
# print(yt_cls_p) 

m1 = np.matrix(Yts_onehot) 
m2 = np.matrix(yt_cls_p) 
difference = np.abs(m1 - m2) 
# print(difference) 

correct_p = np.where(~difference.any(axis=1))[0] 
accuracy_p = len(correct_p)/len(difference) 
print("For Polynomial")
print(len(correct_p)) 
print(accuracy_p)

For Linear
30
0.7692307692307693
wp= [[-0.76299101  1.13822047  0.62477054]
 [ 0.6014925  -0.88680328  0.28531078]
 [ 0.59784609 -0.10575032 -0.49209577]
 [-0.85299054  2.07290305 -1.2199125 ]
 [ 0.14176955 -3.06489748  2.92312792]
 [-0.01193797  0.23828328 -0.22634531]
 [-0.12685437 -0.44906348  0.57591784]
 [-0.0345378  -0.02301658  0.05755437]
 [ 0.0405222  -0.19925454  0.15873235]
 [ 0.00558587  0.31463436 -0.32022024]
 [ 0.09555557 -0.10296338  0.00740781]
 [-0.14809056  1.04541241 -0.89732185]
 [ 0.0906437  -0.37729444  0.28665074]
 [-0.07777166  1.0010156  -0.92324394]
 [ 0.12824961 -1.27034815  1.14209854]]
For Polynomial
38
0.9743589743589743


In [3]:
print("yt_est_p")
print(yt_est_p)

yt_est_p
[[ 4.39804651e+12  2.19902326e+12  4.39804651e+12]
 [ 2.19902326e+12 -1.09951163e+12  3.29853488e+12]
 [ 4.39804651e+12  3.29853488e+12  6.59706977e+12]
 [ 3.29853488e+12  5.19943718e-01  3.29853488e+12]
 [ 5.49755814e+12  3.29853488e+12  5.49755814e+12]
 [ 5.49755814e+12  3.29853488e+12  5.49755814e+12]
 [ 5.49755814e+12  3.29853488e+12  5.49755814e+12]
 [ 3.29853488e+12  2.19902326e+12  3.29853488e+12]
 [ 1.09951163e+12  1.09951163e+12  3.29853488e+12]
 [ 3.29853488e+12  1.09951163e+12  5.49755814e+12]
 [ 2.19902326e+12  2.19902326e+12  6.59706977e+12]
 [ 4.39804651e+12  2.19902326e+12  3.29853488e+12]
 [ 4.39804651e+12  3.29853488e+12  6.59706977e+12]
 [ 3.29853488e+12  1.09951163e+12  4.39804651e+12]
 [ 3.29853488e+12  3.29853488e+12  5.49755814e+12]
 [ 4.39804651e+12  3.29853488e+12  7.69658139e+12]
 [ 4.39804651e+12  2.19902326e+12  4.39804651e+12]
 [ 4.39804651e+12  2.19902326e+12  5.49755814e+12]
 [ 4.39804651e+12  4.39804651e+12  5.49755814e+12]
 [ 3.29853488e+12  1.0

In [4]:
print("yt_cls_p")
print(yt_cls_p) 

yt_cls_p
[[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1]]


In [12]:
print(iris_dataset.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.